name: JStatsCore
version: 1.0
main: com.driga.jstatscore.JStatsCore
authors: [ Jusai ]
website: https://github.com/Rodriga0
depend: [PowerNBT, ProtocolLib]
commands:
  jsc:
  stats:
    aliases: [ stat, atributos, atributo ]
  forms:
    aliases: [ form, formas, forma, modos, modo ]
